compilers:
  - name: venom
    queue: venom
    exec_params:
      venom: True
  - name: default
    queue: default
    exec_params:
      venom: False

queues:
  venom:
    host: queue_optimization_gas
    port: 5672
  default:
    host: queue_optimization_gas
    port: 5672

db:
  host: localhost
  port: 27017
input_strategies: [1]
# for logging level reference https://docs.python.org/3/library/logging.html#logging-levels
verbosity: DEBUG
extra_flags: []
