compilers:
  - name: venom
    queue:
      host: localhost
      port: 5672
    exec_params:
      venom: True
  - name: default
    queue:
      host: localhost
      port: 5673
    exec_params:
      venom: False
db:
  host: localhost
  port: 27017
input_strategies: [1]
# for logging level reference https://docs.python.org/3/library/logging.html#logging-levels
verbosity: INFO
extra_flags: []