version: '3'
services:
  generator:
    image: registry.statemind.io/vyper-fuzzer-generator:v0.1.0-dev0
    command:
      - python3.10
      - run.py
      - /corpus
    networks:
      - db
      - queue_opt_gas
    environment:
      PYTHONPATH: /app
      DB_HOST: mongodb
      DB_PORT: 27017
      QUEUE_BROKER_HOST: queue_optimization_gas
      QUEUE_BROKER_PORT: 5672
    depends_on:
      - mongodb
      - queue_optimization_gas
    volumes:
      - corpus:/corpus
  queue_optimization_gas:
    image: rabbitmq:management
    networks:
      - queue_opt_gas
    ports:
      - "56720:5672"
      - "15672:15672"
  compiler_optimization_gas:
    image: registry.statemind.io/vyper-fuzzer-generator:v0.1.0-dev0
    environment:
      PARAMS: ""
      PYTHONPATH: /app
      DB_HOST: mongodb
      DB_PORT: 27017
      QUEUE_BROKER_HOST: queue_optimization_gas
      QUEUE_BROKER_PORT: 5672
    depends_on:
      - mongodb
      - queue_optimization_gas
    command:
      - python3.10
      - tests/integration_runner/compile.py
    networks:
      - db
      - queue_opt_gas
  mongodb:
    image: mongo
    networks:
      - db
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db

networks:
  db:
    driver: bridge
  queue_opt_gas:
    driver: bridge

volumes:
  db:
  corpus:
  # TODO: come up with queues' volumes to not lose it in case of a failure
